Repository boostcamp-2020/Project10-Twitter, pull requests merged in 2020-12, with the labels that each got.

#79 [feat] 글 삭제 API 구현 및 알람 생성 조회 수정 API 구현, 트윗 생성, 조회 API 수정
  be/src/app.ts
  be/src/lib/jwt-token.ts
  be/src/models/notification.ts
  be/src/models/tweet.ts
  be/src/models/user.ts
  be/src/resolvers/index.ts
  be/src/schema/index.ts
  be/src/services/auth.ts
  be/src/services/index.ts
  be/src/services/notification/index.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/deleteTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/index.ts
  be/src/services/user/getUser.ts
  be/src/services/user/modifyUser.ts
Labels: API, BE

#80 [refac] 메인 페이지, 로그인 페이지 수정
  fe/package-lock.json
  fe/package.json
  fe/src/components/atoms/Text/index.tsx
  fe/src/components/atoms/Text/styled.ts
  fe/src/components/molecules/Button/index.tsx
  fe/src/components/molecules/IconLabel/index.tsx
  fe/src/components/molecules/IconLabel/styled.ts
  fe/src/components/molecules/TitleSubText/index.tsx
  fe/src/components/molecules/TitleSubText/titleSubText.stories.tsx
  fe/src/components/molecules/UserInfo/index.tsx
  fe/src/components/molecules/UserInfo/styled.ts
  fe/src/components/molecules/UserInfo/userInfo.stories.tsx
  fe/src/components/molecules/UserModal/index.tsx
  fe/src/components/molecules/UserModal/styled.ts
  fe/src/components/organisms/LoginLeftSection/styled.ts
  fe/src/components/organisms/LoginRightSection/index.tsx
  fe/src/components/organisms/LoginRightSection/styled.ts
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/home/styled.ts
Labels: FE, Refactor, UI

#82 [feat] 유저 페이지 컴포넌트 및 페이지 조립, 커스텀 훅 생성, css 안먹는 현상 수정, 유저쿼리로 리팩토링
  fe/package-lock.json
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/atoms/ProfileImg/index.tsx
  fe/src/components/atoms/Text/styled.ts
  fe/src/components/molecules/IconLabel/styled.ts
  fe/src/components/molecules/UserModal/index.tsx
  fe/src/components/molecules/UserModal/styled.ts
  fe/src/components/organisms/LoginLeftSection/styled.ts
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/SideBar/styled.ts
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/components/organisms/UserDetailContainer/styled.ts
  fe/src/graphql/getList.gql
  fe/src/graphql/getMyInfo.gql
  fe/src/graphql/getTweetList.gql
  fe/src/graphql/getUserDetail.gql
  fe/src/graphql/getUserTweetList.gql
  fe/src/hooks/useDisplay.ts
  fe/src/hooks/useOnTextChange.ts
  fe/src/pages/[userId]/index.tsx
  fe/src/pages/[userId]/styled.ts
  fe/src/pages/_app.tsx
  fe/src/pages/callback/callback.ts
  fe/src/pages/home/index.tsx
Labels: FE, Refactor, UI

#81 [feat] 로컬 회원가입, 회원 정보 수정, 이미지 업로드 API 작성 및 리팩토링 작업
  be/.gitignore
  be/package-lock.json
  be/package.json
  be/src/app.ts
  be/src/lib/hash-password.ts
  be/src/lib/jwt-token.ts
  be/src/models/notification.ts
  be/src/models/tweet.ts
  be/src/resolvers/index.ts
  be/src/schema/index.ts
  be/src/services/auth.ts
  be/src/services/index.ts
  be/src/services/notification/index.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/deleteTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/upload.ts
  be/src/services/user/addUser.ts
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
Labels: API, BE, Refactor

#84 [feat] heart, unheart API, 유저 정보 수정 API , 유저 디테일 트윗 및 자식 트윗 조회 API , 스키마 및 리졸버 리팩토링
  be/package-lock.json
  be/package.json
  be/src/app.ts
  be/src/models/tweet.ts
  be/src/models/user.ts
  be/src/resolvers/file.ts
  be/src/resolvers/index.ts
  be/src/resolvers/notification.ts
  be/src/resolvers/tweet.ts
  be/src/resolvers/user.ts
  be/src/schema/common.gql
  be/src/schema/file.gql
  be/src/schema/index.ts
  be/src/schema/notification.gql
  be/src/schema/tweet.gql
  be/src/schema/user.gql
  be/src/services/auth/index.ts
  be/src/services/index.ts
  be/src/services/notification/addNotification.ts
  be/src/services/notification/getNotification.ts
  be/src/services/notification/index.ts
  be/src/services/notification/modifyNotification.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/common.ts
  be/src/services/tweet/deleteTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/index.ts
  be/src/services/tweet/modifyTweet.ts
  be/src/services/upload/index.ts
  be/src/services/user/addUser.ts
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
Labels: BE, Bug, Refactor

#88 [feat] 최신 조회, 하트 글 조회 API 작성 및 리팩토링 진행
  be/src/lib/utilty.ts
  be/src/models/user.ts
  be/src/resolvers/notification.ts
  be/src/resolvers/tweet.ts
  be/src/resolvers/user.ts
  be/src/schema/notification.gql
  be/src/schema/tweet.gql
  be/src/schema/user.gql
  be/src/services/auth/index.ts
  be/src/services/notification/addNotification.ts
  be/src/services/notification/getNotification.ts
  be/src/services/notification/modifyNotification.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/deleteTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/index.ts
  be/src/services/tweet/modifyTweet.ts
  be/src/services/user/addUser.ts
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
Labels: API, BE, Bug, DB, Refactor, auth

#90 [feat] tab bar 화면 전환 방식 변경, follow 페이지 구현, 글 추가 기능 구현
  fe/src/components/molecules/Button/index.tsx
  fe/src/components/molecules/TabBar/index.tsx
  fe/src/components/molecules/UserInfo/index.tsx
  fe/src/components/organisms/LoginLeftSection/index.tsx
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/PageLayout/styled.ts
  fe/src/components/organisms/UserCard/index.tsx
  fe/src/components/organisms/UserCard/styled.ts
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/graphql/addBasicTweet.gql
  fe/src/graphql/getFollowerList.gql
  fe/src/graphql/getFollowingList.gql
  fe/src/graphql/getMyInfo.gql
  fe/src/hooks/useOnTabChange.ts
  fe/src/libs/index.ts
  fe/src/libs/index.tsx
  fe/src/pages/[userId]/follow.tsx
  fe/src/pages/[userId]/index.tsx
  fe/src/pages/_app.tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/home/styled.ts
Labels: FE, Refactor

#93 [fix] 빈 이름 나오는 현상 수정
  be/src/lib/utilty.ts
  be/src/services/auth/index.ts
  be/src/services/user/addUser.ts
Labels: BE, Bug

#92 [feat] 백엔드 3주차
  be/.gitignore
  be/package-lock.json
  be/package.json
  be/src/app.ts
  be/src/lib/hash-password.ts
  be/src/lib/jwt-token.ts
  be/src/lib/utilty.ts
  be/src/models/notification.ts
  be/src/models/tweet.ts
  be/src/models/user.ts
  be/src/resolvers/file.ts
  be/src/resolvers/index.ts
  be/src/resolvers/notification.ts
  be/src/resolvers/tweet.ts
  be/src/resolvers/user.ts
  be/src/schema/common.gql
  be/src/schema/file.gql
  be/src/schema/index.ts
  be/src/schema/notification.gql
  be/src/schema/tweet.gql
  be/src/schema/user.gql
  be/src/services/auth.ts
  be/src/services/auth/index.ts
  be/src/services/index.ts
  be/src/services/notification/addNotification.ts
  be/src/services/notification/getNotification.ts
  be/src/services/notification/index.ts
  be/src/services/notification/modifyNotification.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/common.ts
  be/src/services/tweet/deleteTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/index.ts
  be/src/services/tweet/modifyTweet.ts
  be/src/services/upload/index.ts
  be/src/services/user/addUser.ts
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
Labels: API, BE, Bug, Refactor, auth

#91 [feat] 리팩토링, 메인 페이지, 유저 상세 페이지, 팔로우/팔로워 페이지, 검색 페이지 구현
  fe/.eslintrc
  fe/package-lock.json
  fe/package.json
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/atoms/ProfileImg/index.tsx
  fe/src/components/atoms/Text/index.tsx
  fe/src/components/atoms/Text/styled.ts
  fe/src/components/molecules/Button/index.tsx
  fe/src/components/molecules/IconLabel/index.tsx
  fe/src/components/molecules/IconLabel/styled.ts
  fe/src/components/molecules/SearchBar/index.tsx
  fe/src/components/molecules/TabBar/index.tsx
  fe/src/components/molecules/TitleSubText/index.tsx
  fe/src/components/molecules/TitleSubText/titleSubText.stories.tsx
  fe/src/components/molecules/UserInfo/index.tsx
  fe/src/components/molecules/UserInfo/styled.ts
  fe/src/components/molecules/UserInfo/userInfo.stories.tsx
  fe/src/components/molecules/UserPopover/index.tsx
  fe/src/components/molecules/UserPopover/styled.ts
  fe/src/components/organisms/LoginLeftSection/index.tsx
  fe/src/components/organisms/LoginLeftSection/styled.ts
  fe/src/components/organisms/LoginRightSection/index.tsx
  fe/src/components/organisms/LoginRightSection/styled.ts
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/PageLayout/index.tsx
  fe/src/components/organisms/PageLayout/styled.ts
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/SideBar/styled.ts
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/UserCard/index.tsx
  fe/src/components/organisms/UserCard/styled.ts
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/components/organisms/UserDetailContainer/styled.ts
  fe/src/graphql/addBasicTweet.gql
  fe/src/graphql/getFollowerList.gql
  fe/src/graphql/getFollowingList.gql
  fe/src/graphql/getList.gql
  fe/src/graphql/getMyInfo.gql
  fe/src/graphql/getSearchedTweetList.gql
  fe/src/graphql/getSearchedUserList.gql
  fe/src/graphql/getTweetList.gql
  fe/src/graphql/getUserAllTweetList.gql
  fe/src/graphql/getUserDetail.gql
  fe/src/graphql/getUserTweetList.gql
  fe/src/hooks/useDisplay.ts
  fe/src/hooks/useOnTabChange.ts
  fe/src/hooks/useOnTextChange.ts
  fe/src/libs/index.ts
  fe/src/libs/index.tsx
  fe/src/pages/[userId]/follow.tsx
  fe/src/pages/[userId]/index.tsx
  fe/src/pages/[userId]/styled.ts
  fe/src/pages/_app.tsx
  fe/src/pages/callback/callback.ts
  fe/src/pages/explore/index.tsx
  fe/src/pages/explore/styled.ts
  fe/src/pages/home/index.tsx
  fe/src/pages/home/styled.ts
Labels: Bug, FE, Refactor

#108 [feat] 팔로우 및 언팔로우 가능, useUserState 및 useMyInfo 커스텀 훅 작성
  fe/src/components/molecules/Button/index.tsx
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/UserCard/index.tsx
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/graphql/followUser.gql
  fe/src/graphql/getUserDetail.gql
  fe/src/graphql/unfollowUser.gql
  fe/src/hooks/useMyInfo.ts
  fe/src/hooks/useUserState.ts
  fe/src/utilitys/index.ts
Labels: FE, Refactor

#107 [feat] [feat] 하트한 유저 리스트 및 리트윗한 유저 리스트 조회 API
  be/src/resolvers/user.ts
  be/src/schema/user.gql
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
Labels: API, BE

#110 [feat] 하트한 유저 리스트 및 리트윗한 유저 리스트 조회 API
  be/src/resolvers/user.ts
  be/src/schema/user.gql
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
Labels: API, BE

#111 [feat] 알림 페이지 구현 및 리트윗 컨테이너 구현
  fe/src/components/atoms/ProfileImg/index.tsx
  fe/src/components/molecules/UserInfo/index.tsx
  fe/src/components/organisms/NotificationContainer/index.tsx
  fe/src/components/organisms/NotificationContainer/styled.ts
  fe/src/components/organisms/ReTweetContainer/index.tsx
  fe/src/components/organisms/ReTweetContainer/styled.ts
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/UserCard/index.tsx
  fe/src/graphql/getNotification.gql
  fe/src/graphql/getTweetList.gql
  fe/src/graphql/updateNotification.gql
  fe/src/pages/home/index.tsx
  fe/src/pages/notifications/[type].tsx
  fe/src/styles/global.css
Labels: FE, UI

#112 [feat] 모달 구현(수정 필요)
  fe/src/components/molecules/Modal/Portal.tsx
  fe/src/components/molecules/Modal/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/pages/_document.tsx
Labels: FE, UI

#113 [fix] 유저가 하트한 트윗 id list 반환
  be/src/schema/user.gql
Labels: BE, Bug

#116 [feat] 메인 페이지 트윗 무한 스크롤 및 useInfiniteScroll custom 훅 작성
  fe/src/graphql/getTweetList.gql
  fe/src/hooks/useInfiniteScroll.ts
  fe/src/libs/apolloClient.ts
  fe/src/pages/_app.tsx
  fe/src/pages/home/index.tsx
Labels: FE

#115 [feat] 동적 라우팅 및 유저 디테일 추가 구현
  fe/.eslintrc
  fe/src/components/molecules/Footer/index.tsx
  fe/src/components/organisms/MainContainer/index.tsx
  fe/src/components/organisms/NotificationContainer/index.tsx
  fe/src/components/organisms/ReTweetContainer/index.tsx
  fe/src/components/organisms/ReTweetContainer/styled.ts
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/TweetContainer/tweetcontainer.stories.tsx
  fe/src/components/organisms/TweetStateContainer/index.tsx
  fe/src/components/organisms/UserCard/index.tsx
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/graphql/getHeartTweetList.gql
  fe/src/graphql/getNotification.gql
  fe/src/graphql/getSearchedTweetList.gql
  fe/src/graphql/getTweetList.gql
  fe/src/graphql/getUserAllTweetList.gql
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/[userId]/follow.tsx
  fe/src/pages/[userId]/follow/[[...type]].tsx
  fe/src/pages/[userId]/index.tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/explore/index.tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
  fe/src/utilitys/index.ts
Labels: FE, UI

#117 [feat] modal layout 수정 및 추가/댓글 모달 생성
  fe/src/components/atoms/TextArea/index.tsx
  fe/src/components/molecules/Modal/index.tsx
  fe/src/components/molecules/Modal/styled.ts
  fe/src/components/molecules/TweetFooter/index.tsx
  fe/src/components/molecules/TweetFooter/styled.ts
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/TweetModal/NewTweetModal.tsx
  fe/src/components/organisms/TweetModal/ReplyModal.tsx
Labels: FE, UI

#118 [fix] 최신 트윗 가져올 수 있도록 수정
  be/src/schema/tweet.gql
  be/src/services/tweet/getTweet.ts
Labels: BE, Bug

#119 [refactor] 모델 수정 및 리펙토링
  be/.env.example
  be/.eslintrc
  be/package-lock.json
  be/package.json
  be/src/app.ts
  be/src/models/notification.ts
  be/src/models/user.ts
  be/src/resolvers/file.ts
  be/src/resolvers/notification.ts
  be/src/schema/notification.gql
  be/src/schema/user.gql
  be/src/services/auth/index.ts
  be/src/services/notification/addNotification.ts
  be/src/services/notification/getNotification.ts
  be/src/services/notification/index.ts
  be/src/services/notification/modifyNotification.ts
  be/src/services/tweet/common.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/modifyTweet.ts
  be/src/services/user/addUser.ts
Labels: API, BE, Refactor

#120 [feat] 이미지 업로드 구현 및 알람 페이지 수정
  fe/package-lock.json
  fe/package.json
  fe/src/components/molecules/TweetFooter/index.tsx
  fe/src/components/molecules/UploadImg/index.tsx
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/NewTweetContainer/newTweetContainer.stories.tsx
  fe/src/components/organisms/NewTweetContainer/styled.ts
  fe/src/components/organisms/NotificationContainer/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/SideBar/sideBar.stories.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/TweetContainer/tweetcontainer.stories.tsx
  fe/src/components/organisms/TweetDetailContainer/index.tsx
  fe/src/components/organisms/TweetStateContainer/index.tsx
  fe/src/components/organisms/UserCard/index.tsx
  fe/src/graphql/getChildTweetList.gql
  fe/src/graphql/getHeartTweetList.gql
  fe/src/graphql/getMentionNotification.gql
  fe/src/graphql/getMyInfo.gql
  fe/src/graphql/getNotification.gql
  fe/src/graphql/getNotificationCount.gql
  fe/src/graphql/getSearchedTweetList.gql
  fe/src/graphql/getTweetList.gql
  fe/src/graphql/getUserAllTweetList.gql
  fe/src/graphql/getUserTweetList.gql
  fe/src/graphql/imageUpload.gql
  fe/src/graphql/updateNotification.gql
  fe/src/hooks/useMyInfo.ts
  fe/src/libs/apolloClient.ts
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/[userId]/follow/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
  fe/src/pages/status/[tweetId].tsx
Labels: FE, UI

#123 [feat] 무한 스크롤 적용 및 최신 데이터 캐시에 저장후 머지
  fe/src/graphql/getChildTweetList.gql
  fe/src/graphql/getFollowerList.gql
  fe/src/graphql/getFollowingList.gql
  fe/src/graphql/getNotification.gql
  fe/src/graphql/getSearchedTweetList.gql
  fe/src/graphql/getSearchedUserList.gql
  fe/src/graphql/getUserAllTweetList.gql
  fe/src/graphql/getUserDetail.gql
  fe/src/graphql/getUserTweetList.gql
  fe/src/hooks/useInfiniteScroll.ts
  fe/src/libs/apolloClient.ts
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/status/[tweetId].tsx
Labels: FE

#122 [fix] 트윗 검색 컨디션 수정
  be/src/services/tweet/getTweet.ts
Labels: BE, Bug

#121 [feat] 리트윗, 댓글, 좋아요한 사람 모달, 리트윗한 사람 모달 생성
  fe/src/components/molecules/InputContainer/index.tsx
  fe/src/components/molecules/InputContainer/styled.ts
  fe/src/components/molecules/Modal/Portal.tsx
  fe/src/components/molecules/TitleSubText/index.tsx
  fe/src/components/organisms/LoginRightSection/index.tsx
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/NewTweetContainer/styled.ts
  fe/src/components/organisms/NotificationContainer/index.tsx
  fe/src/components/organisms/ReTweetContainer/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/SignupModal/index.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/TweetDetailContainer/index.tsx
  fe/src/components/organisms/TweetModal/HeartListModal.tsx
  fe/src/components/organisms/TweetModal/NewTweetModal.tsx
  fe/src/components/organisms/TweetModal/ReplyModal.tsx
  fe/src/components/organisms/TweetModal/RetweetListModal.tsx
  fe/src/components/organisms/TweetModal/RetweetModal.tsx
  fe/src/components/organisms/TweetModal/index.ts
  fe/src/graphql/addReplyTweet.gql
  fe/src/graphql/addRetweet.gql
  fe/src/graphql/getHeartUserList.gql
  fe/src/graphql/getRetweetUserList.gql
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/home/index.tsx
Labels: API, UI

#126 [feat] 모달 쉘로우 라우팅, 트윗 삭제 기능 및 캐시 업데이트 , 시간 추가 및 리팩토링
  fe/package-lock.json
  fe/package.json
  fe/src/components/atoms/Text/index.tsx
  fe/src/components/atoms/Text/styled.ts
  fe/src/components/atoms/icons/X.tsx
  fe/src/components/atoms/icons/index.ts
  fe/src/components/molecules/Modal/index.tsx
  fe/src/components/organisms/NotificationContainer/index.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/TweetContainer/styled.ts
  fe/src/components/organisms/TweetDetailContainer/index.tsx
  fe/src/components/organisms/TweetDetailContainer/styled.ts
  fe/src/components/organisms/TweetStateContainer/index.tsx
  fe/src/components/organisms/UserCard/index.tsx
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/graphql/deleteTweet.gql
  fe/src/graphql/getChildTweetList.gql
  fe/src/graphql/getHeartTweetList.gql
  fe/src/graphql/getMentionNotification.gql
  fe/src/graphql/getNotification.gql
  fe/src/graphql/getSearchedTweetList.gql
  fe/src/graphql/getTweetDetail.gql
  fe/src/graphql/getTweetList.gql
  fe/src/graphql/getUserAllTweetList.gql
  fe/src/graphql/getUserTweetList.gql
  fe/src/hooks/useDisplayWithShallow.ts
  fe/src/libs/authProvider.tsx
  fe/src/libs/index.tsx
  fe/src/libs/utility.ts
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/_app.tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
  fe/src/pages/status/[[...type]].tsx
  fe/src/utilitys/index.ts
Labels: FE

#124 [feat] 알람 페이지 무한 스크롤 및 캐시 업데이트
  fe/src/components/atoms/icons/FullHeart.tsx
  fe/src/components/atoms/icons/index.ts
  fe/src/components/organisms/NotificationContainer/FollowContainer/FollowContainer.stories.tsx
  fe/src/components/organisms/NotificationContainer/FollowContainer/index.tsx
  fe/src/components/organisms/NotificationContainer/FollowContainer/styled.ts
  fe/src/components/organisms/NotificationContainer/HeartContainer/HeartContainer.stories.tsx
  fe/src/components/organisms/NotificationContainer/HeartContainer/index.tsx
  fe/src/components/organisms/NotificationContainer/HeartContainer/styled.ts
  fe/src/components/organisms/NotificationContainer/index.tsx
  fe/src/graphql/getMentionNotification.gql
  fe/src/graphql/getNotification.gql
  fe/src/hooks/useHeartState.ts
  fe/src/libs/apolloClient.ts
  fe/src/pages/notifications/[[...type]].tsx
Labels: FE, UI

#125 [refac] 노티피케이션 수정
  be/src/schema/notification.gql
  be/src/services/notification/getNotification.ts
  be/src/services/tweet/modifyTweet.ts
Labels: API, BE, Refactor

#127 [fix] 트윗 삭제 로직 수정 및 알람 생성자를 giver로 수정 및 로직 수정
  be/src/models/notification.ts
  be/src/schema/notification.gql
  be/src/services/notification/addNotification.ts
  be/src/services/notification/getNotification.ts
  be/src/services/notification/index.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/deleteTweet.ts
  be/src/services/tweet/modifyTweet.ts
  be/src/services/user/modifyUser.ts
Labels: BE, Bug

#130 [fix] 풀리퀘 머지하면서 일어난 버그 수정
  fe/src/components/organisms/NotificationContainer/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
Labels: Bug, FE

#129 [feat] 유저 무한 스크롤 모든 페이지 적용 및 회원 가입 구현
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/molecules/InputContainer/index.tsx
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/SignupModal/index.tsx
  fe/src/components/organisms/SignupModal/styled.ts
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/graphql/addUser.gql
  fe/src/graphql/getFollowerList.gql
  fe/src/graphql/getFollowingList.gql
  fe/src/graphql/getSearchedTweetList.gql
  fe/src/graphql/getSearchedUserList.gql
  fe/src/graphql/getUserDetail.gql
  fe/src/libs/apolloClient.ts
  fe/src/pages/[userId]/follow/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
Labels: FE, UI

#131 [feat] user 무한 스크롤 순서 위해 sort, user 팔로워 수 받아오는 쿼리 작성
  be/src/resolvers/user.ts
  be/src/schema/user.gql
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
Labels: API, BE

#132 [fix] 이미지 삭제 버튼 변경, 최신 notification id 조건 변경
  fe/src/components/molecules/UploadImg/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
Labels: FE

#133 [feat] 로딩 화면 추가
  fe/src/components/molecules/Loading/Point.ts
  fe/src/components/molecules/Loading/Wave.ts
  fe/src/components/molecules/Loading/WaveGroup.ts
  fe/src/components/molecules/Loading/index.tsx
  fe/src/components/molecules/Loading/styled.ts
  fe/src/components/organisms/TweetDetailContainer/index.tsx
  fe/src/components/organisms/TweetModal/HeartListModal.tsx
  fe/src/components/organisms/TweetModal/RetweetListModal.tsx
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/libs/authProvider.tsx
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/[userId]/follow/[[...type]].tsx
  fe/src/pages/callback/index.tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/status/[[...type]].tsx
Labels: FE, UI

#134 [feat] be 4주차 진행 사항
  be/.env.example
  be/.eslintrc
  be/package-lock.json
  be/package.json
  be/src/app.ts
  be/src/models/notification.ts
  be/src/models/user.ts
  be/src/resolvers/file.ts
  be/src/resolvers/notification.ts
  be/src/resolvers/user.ts
  be/src/schema/notification.gql
  be/src/schema/tweet.gql
  be/src/schema/user.gql
  be/src/services/auth/index.ts
  be/src/services/notification/addNotification.ts
  be/src/services/notification/getNotification.ts
  be/src/services/notification/index.ts
  be/src/services/notification/modifyNotification.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/common.ts
  be/src/services/tweet/deleteTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/modifyTweet.ts
  be/src/services/user/addUser.ts
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
Labels: API, BE, Bug, Refactor

#138 [refac] 절대 경로 설정 및 인증 어서러 헤더에서 쿠키로 변경
  be/package.json
  be/src/app.ts
  be/src/libs/hash-password.ts
  be/src/libs/jwt-token.ts
  be/src/libs/utiltys.ts
  be/src/resolvers/file.ts
  be/src/resolvers/notification.ts
  be/src/resolvers/tweet.ts
  be/src/resolvers/user.ts
  be/src/schema/user.gql
  be/src/services/auth/index.ts
  be/src/services/notification/addNotification.ts
  be/src/services/notification/getNotification.ts
  be/src/services/notification/modifyNotification.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/deleteTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/modifyTweet.ts
  be/src/services/user/addUser.ts
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
  be/tsconfig.json
Labels: BE, Refactor

#139 [feat] 하트 캐시 업데이트 부분 수정 및 댓글 시 캐시 업데이트
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/NotificationContainer/index.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/TweetModal/ReplyModal.tsx
  fe/src/components/organisms/TweetModal/RetweetListModal.tsx
  fe/src/components/organisms/TweetModal/RetweetModal.tsx
  fe/src/components/organisms/index.ts
  fe/src/graphql/tweet/getTweet.gql
  fe/src/hooks/useHeartState.ts
  fe/src/libs/index.tsx
  fe/src/libs/utility.ts
  fe/src/pages/notifications/[[...type]].tsx
Labels: FE

#141 [feat] 메인 페이지 서버사이드 렌더링
  fe/package-lock.json
  fe/package.json
  fe/src/libs/apolloClient.ts
  fe/src/pages/home/index.tsx
Labels: FE

#146 [feat] 무한 스크롤 데이터와 함께 사용하는 커스텀 훅 및 여러 커스텀 훅 생성, 검색 페이지, 트윗 디테일 페이지 서버 사이드 렌더링
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/TweetDetailContainer/index.tsx
  fe/src/hooks/index.ts
  fe/src/hooks/useDataWithInfiniteScroll.ts
  fe/src/hooks/useDisplayWithShallow.ts
  fe/src/hooks/useHomeTweetListInfiniteScroll.ts
  fe/src/hooks/useInfiniteScroll.ts
  fe/src/hooks/useTypeRouter.ts
  fe/src/libs/index.tsx
  fe/src/libs/utility.ts
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/status/[[...type]].tsx
Labels: FE, Refactor

#147 [feat] 트윗에 있는 리트윗에도 자식 , 리트윗, 하트 숫자 반환
  be/src/schema/tweet.gql
  be/src/services/tweet/common.ts
Labels: BE

#142 [feat] 유저 정보 수정 API 추가 구현
  be/src/resolvers/user.ts
  be/src/schema/user.gql
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
Labels: API, BE

#144 [refac] comment, retweet notification 추가할 때 giver도 저장
  be/src/services/tweet/addTweet.ts
Labels: BE, Refactor

#143 [feat] 모달 수정 및 서버사이드 랜더링 캐시 업데이트 기능 구현
  fe/package-lock.json
  fe/package.json
  fe/src/components/molecules/Modal/Portal.tsx
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/SignupModal/index.tsx
  fe/src/components/organisms/TweetModal/NewTweetModal.tsx
  fe/src/components/organisms/TweetModal/ReplyModal.tsx
  fe/src/components/organisms/TweetModal/RetweetModal.tsx
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/components/organisms/UserEditModal/index.tsx
  fe/src/components/organisms/UserEditModal/styled.ts
  fe/src/components/organisms/index.ts
  fe/src/graphql/tweet/getTweet.gql
  fe/src/graphql/user/index.ts
  fe/src/graphql/user/modifyUser.gql
  fe/src/hooks/index.ts
  fe/src/hooks/useApollo.ts
  fe/src/libs/apolloClient.ts
  fe/src/libs/index.tsx
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/_app.tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
  fe/src/pages/status/[[...type]].tsx
  fe/src/styles/global.css
Labels: FE, UI

#149 [feat] 하트 캐시 업데이트 구현 및 캐시 머지 에러 수정
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/TweetDetailContainer/index.tsx
  fe/src/components/organisms/TweetModal/HeartListModal.tsx
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/graphql/custom/customQuery.gql
  fe/src/graphql/tweet/getTweet.gql
  fe/src/hooks/useHeartState.ts
  fe/src/libs/apolloClient.ts
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/notifications/[[...type]].tsx
  fe/src/pages/status/[[...type]].tsx
Labels: Bug, FE, Refactor

#150 [feat] 로딩 서클 컴포넌트 추가 및 모든 무한스크롤에 적용, 훅들 사용해서 리팩토링
  fe/src/components/molecules/LoadingCircle/index.tsx
  fe/src/components/molecules/index.ts
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/hooks/index.ts
  fe/src/hooks/useDataWithInfiniteScroll.ts
  fe/src/hooks/useHomeTweetListInfiniteScroll.ts
  fe/src/hooks/useInfiniteScroll.ts
  fe/src/hooks/useOnTabChange.ts
  fe/src/libs/apolloClient.ts
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/[userId]/follow/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
  fe/src/pages/status/[[...type]].tsx
Labels: Bug, FE, Refactor

#151 [fix] 모든 트윗 내용물에서 자식 갯수, 하트 개수, 리트윗 개수 반환
  be/src/services/notification/common.ts
  be/src/services/notification/getNotification.ts
  be/src/services/tweet/common.ts
Labels: BE, Bug

#152 [fix] 머지후 버그 픽스
  fe/src/components/organisms/NotificationContainer/index.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/TweetDetailContainer/index.tsx
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
  fe/src/pages/status/[[...type]].tsx
Labels: Bug, FE

#154 [fix] 자식 숫자 버그 수정 및 자식 트윗 순서 변경
  be/src/services/notification/common.ts
  be/src/services/tweet/common.ts
  be/src/services/tweet/getTweet.ts
Labels: BE, Bug

#155 [fix] 처음 쿠키가 아폴로 클라이언트에 없어서 생기는 인증 버그 수정
  fe/src/libs/apolloClient.ts
  fe/src/libs/index.tsx
  fe/src/pages/callback/index.tsx
Labels: Bug, FE

#157 [fix] URL 하드 코딩된 부분 변경
  be/.env.example
  be/src/app.ts
  be/src/services/auth/index.ts
  be/src/services/upload/index.ts
Labels: BE, Refactor

#156 [refactor] 유저 카드 간격 수정
  fe/.gitignore
  fe/config/config.example.ts
  fe/src/components/organisms/LoginRightSection/index.tsx
  fe/src/components/organisms/UserCard/index.tsx
  fe/src/components/organisms/UserCard/styled.ts
  fe/src/libs/apolloClient.ts
  fe/tsconfig.json
Labels: FE, UI

#160 [chore] 프론트 서버 url dotenv 적용
  fe/.env.example
  fe/.gitignore
  fe/config/config.example.ts
  fe/next.config.js
  fe/package-lock.json
  fe/package.json
  fe/src/components/organisms/LoginRightSection/index.tsx
  fe/src/libs/apolloClient.ts
  fe/tsconfig.json
Labels: Development Setting, FE

#161 [chore] 서버 pm2 스크립트 작성 및 dotenv 변경
  be/.env.example
  be/package-lock.json
  be/package.json
Labels: BE, Development Setting

#162 [chore] 프론트 pm2 스크립트 작성 및 dotenv 변경
  fe/.env.example
  fe/package-lock.json
  fe/package.json
  fe/src/components/organisms/LoginRightSection/index.tsx
  fe/src/libs/apolloClient.ts
Labels: Development Setting, FE

#163 [fix] 빌드를위해 에러 제거
  fe/src/components/atoms/Input/input.stories.tsx
  fe/src/components/molecules/ComponentLoading/index.tsx
  fe/src/components/molecules/Loading/index.tsx
  fe/src/components/molecules/LoginForm/loginForm.stories.tsx
  fe/src/components/molecules/SearchBar/index.tsx
  fe/src/components/molecules/SearchBar/searchBar.stories.tsx
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/NotificationContainer/HeartContainer/HeartContainer.stories.tsx
  fe/src/components/organisms/NotificationContainer/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/hooks/useDataWithInfiniteScroll.ts
  fe/src/hooks/useHomeTweetListInfiniteScroll.ts
  fe/src/hooks/useInfiniteScroll.ts
  fe/src/hooks/useUserState.ts
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/[userId]/follow/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
  fe/src/pages/status/[[...type]].tsx
Labels: Bug, FE

#164 [refactor] 대소문자 맞지 않는 폴더 삭제
  fe/src/components/atoms/icons/Comment.tsx
  fe/src/components/atoms/icons/Explore.tsx
  fe/src/components/atoms/icons/FullHeart.tsx
  fe/src/components/atoms/icons/Heart.tsx
  fe/src/components/atoms/icons/Home.tsx
  fe/src/components/atoms/icons/Notifications.tsx
  fe/src/components/atoms/icons/Picture.tsx
  fe/src/components/atoms/icons/Profiles.tsx
  fe/src/components/atoms/icons/Retweet.tsx
  fe/src/components/atoms/icons/Search.tsx
  fe/src/components/atoms/icons/Twitter.tsx
  fe/src/components/atoms/icons/X.tsx
  fe/src/components/atoms/icons/index.ts
  fe/src/components/organisms/ReTweetContainer/styled.ts
Labels: FE, Refactor

#168 [refactor] componentLoading 제거
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
Labels: FE, Refactor

#167 [refactor] 타입 설정
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/molecules/LoadingCircle/index.tsx
  fe/src/components/molecules/SearchBar/index.tsx
  fe/src/components/organisms/LoginRightSection/index.tsx
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/TweetDetailContainer/index.tsx
  fe/src/hooks/useHeartState.ts
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/[userId]/follow/[[...type]].tsx
  fe/src/pages/callback/index.tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
  fe/src/pages/styled.ts
  fe/src/types/index.ts
Labels: FE, Refactor

#170 [fix] 프로필 페이지 글 쓰기 캐시 업데이트 및 댓글시 트윗 사라지는 에러 수정
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/PageLayout/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/TweetModal/NewTweetModal.tsx
  fe/src/components/organisms/UserDetailContainer/index.tsx
  fe/src/hooks/useHomeTweetListInfiniteScroll.ts
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
Labels: Bug, FE

#169 [fix] 팔로워, 알림 개수 에러 처리
  be/src/services/notification/getNotification.ts
  be/src/services/user/getUser.ts
Labels: API, BE, Bug

#171 [fix] 트윗 삭제시 댓글 수, 리트윗 수 줄어들지 않는 에러 해결 및 css 수정
  fe/src/components/atoms/NoResult/index.tsx
  fe/src/components/atoms/NoResult/styled.ts
  fe/src/components/atoms/index.ts
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/NotificationContainer/FollowContainer/styled.ts
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/graphql/tweet/getTweet.ts
  fe/src/pages/[userId]/[[...type]].tsx
  fe/src/pages/[userId]/follow/[[...type]].tsx
  fe/src/pages/explore/[[...type]].tsx
  fe/src/pages/index.tsx
  fe/src/pages/notifications/[[...type]].tsx
  fe/src/types/index.ts
Labels: Bug, FE, Refactor

#172 [fix] 배포 서버에서 이미지 안올라가던 버그 수정
  be/package-lock.json
  be/package.json
  be/src/app.ts
  be/src/schema/file.gql
  be/src/services/upload/index.ts
Labels: BE, Bug

#176 [chore] be, master readme 작성
  README.md
  be/README.md
Labels: BE, FE, document

#178 [feat] master 1.0.0 version of be
  README.md
  be/.env.example
  be/README.md
  be/package-lock.json
  be/package.json
  be/src/app.ts
  be/src/libs/hash-password.ts
  be/src/libs/jwt-token.ts
  be/src/libs/utiltys.ts
  be/src/resolvers/file.ts
  be/src/resolvers/notification.ts
  be/src/resolvers/tweet.ts
  be/src/resolvers/user.ts
  be/src/schema/file.gql
  be/src/schema/tweet.gql
  be/src/schema/user.gql
  be/src/services/auth/index.ts
  be/src/services/notification/addNotification.ts
  be/src/services/notification/common.ts
  be/src/services/notification/getNotification.ts
  be/src/services/notification/modifyNotification.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/common.ts
  be/src/services/tweet/deleteTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/modifyTweet.ts
  be/src/services/upload/index.ts
  be/src/services/user/addUser.ts
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
  be/tsconfig.json
  fe/.babelrc
  fe/.prettierrc
  fe/.storybook/preset.js
  fe/src/components/atoms/Form/index.tsx
  fe/src/components/atoms/Form/styled.ts
  fe/src/components/atoms/Label/index.tsx
  fe/src/components/atoms/Label/label.stories.tsx
  fe/src/components/atoms/ProfileImg/profileImg.stories.tsx
  fe/src/components/atoms/ProfileImg/styled.ts
  fe/src/components/atoms/Text/text.stories.tsx
  fe/src/components/atoms/TextArea/styled.ts
  fe/src/components/atoms/TextArea/text.stories.tsx
  fe/src/components/molecules/SearchBar/styled.ts
  fe/src/components/molecules/TabBar/index.tsx
  fe/src/components/molecules/TitleSubText/titleSubText.stories.tsx
  fe/src/components/molecules/UserInfo/userInfo.stories.tsx
  fe/src/components/molecules/UserPopover/styled.ts
  fe/src/components/organisms/LoginLeftSection/loginLeftSecion.stories.tsx
  fe/src/components/organisms/LoginRightSection/loginRightSection.stories.tsx
  fe/src/components/organisms/PageLayout/styled.ts
  fe/src/components/organisms/SideBar/styled.ts
  fe/src/components/organisms/UserDetailContainer/styled.ts
  fe/src/hooks/useDisplay.ts
  fe/src/hooks/useOnTextChange.ts
  fe/src/pages/login/styled.ts
Labels: BE, Release
