Repository boostcamp-2020/Project10-Twitter, pull requests merged in 2020-11, with the labels that each got.

#54 [chore] 프론트 엔드 초기설정
  fe/.eslintrc
  fe/.gitignore
  fe/.storybook/main.js
  fe/.storybook/preset.js
  fe/package-lock.json
  fe/package.json
  fe/src/components/atoms/Button/button.stories.tsx
  fe/src/components/atoms/Button/index.tsx
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/atoms/Input/input.stories.tsx
  fe/src/libs/index.ts
  fe/src/pages/index.tsx
  fe/tsconfig.json
Labels: Development Setting, FE

#55 [chore] 기본 설정 관련 모듈 설치 및 폴더 구조, graphql 설정
  be/.env.example
  be/.gitignore
  be/app.ts
  be/controllers/index.ts
  be/package-lock.json
  be/package.json
  be/routes/index.ts
  be/routes/schemas/index.ts
  be/services/index.ts
Labels: BE, Development Setting

#56 [chore] 기본 설정 관련 모듈 설치 및 폴더 구조, graphql , eslint , prettier 설정
  be/.env.example
  be/.eslintrc
  be/.gitignore
  be/.prettierrc
  be/app.ts
  be/controllers/index.ts
  be/package-lock.json
  be/package.json
  be/routes/index.ts
  be/routes/schemas/index.ts
  be/services/index.ts
  be/tsconfig.json
Labels: BE, Development Setting

#57 [chore] 초기 환경설정 및 폴더 구조 설정
  fe/.eslintrc
  fe/.gitignore
  fe/.prettierrc
  fe/.storybook/main.js
  fe/.storybook/preset.js
  fe/package-lock.json
  fe/package.json
  fe/src/components/atoms/Button/button.stories.tsx
  fe/src/components/atoms/Button/index.tsx
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/atoms/Input/input.stories.tsx
  fe/src/libs/index.ts
  fe/src/pages/index.tsx
  fe/tsconfig.json
Labels: Development Setting, FE

#58 [docs] update read me
  README.md
Labels: document

#60 [docs] update issue templates
  .github/ISSUE_TEMPLATE/-----.md
Labels: document

#65 [feat] 사이드 바 아톰 컴포넌트 구현 및 사이드 바 조립
  fe/.eslintrc
  fe/.storybook/main.js
  fe/package-lock.json
  fe/package.json
  fe/src/components/atoms/Button/button.stories.tsx
  fe/src/components/atoms/Button/index.tsx
  fe/src/components/atoms/Text/index.tsx
  fe/src/components/atoms/Text/text.stories.tsx
  fe/src/components/atoms/icons/Explore.tsx
  fe/src/components/atoms/icons/Home.tsx
  fe/src/components/atoms/icons/Notifications.tsx
  fe/src/components/atoms/icons/Profiles.tsx
  fe/src/components/atoms/icons/Twitter.tsx
  fe/src/components/molecules/Button/button.stories.tsx
  fe/src/components/molecules/Button/index.tsx
  fe/src/components/molecules/IconButton/iconButton.stories.tsx
  fe/src/components/molecules/IconButton/index.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/SideBar/sideBar.stories.tsx
Labels: FE, UI

#64 [feat] db 연결 및 모델 연결, apollo server 연결, 팔로우 한 사람의 트윗 가져오기
  be/package-lock.json
  be/package.json
  be/src/app.ts
  be/src/controllers/index.ts
  be/src/models/tweet.ts
  be/src/models/user.ts
  be/src/providers/dbProvider.ts
  be/src/resolvers/index.ts
  be/src/routes/index.ts
  be/src/routes/schemas/index.ts
  be/src/schema/index.ts
  be/src/services/index.ts
Labels: BE, DB, Development Setting

#67 [feat] 사이드 바 조립 및 로그인 페이지 아톰 컴포넌트 구현 및 조립
  fe/.babelrc
  fe/.eslintrc
  fe/package-lock.json
  fe/package.json
  fe/src/components/atoms/Form/index.tsx
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/atoms/Input/input.stories.tsx
  fe/src/components/atoms/Label/index.tsx
  fe/src/components/atoms/Label/label.stories.tsx
  fe/src/components/atoms/ProfileImg/index.tsx
  fe/src/components/atoms/ProfileImg/profileImg.stories.tsx
  fe/src/components/atoms/Text/index.tsx
  fe/src/components/atoms/Text/text.stories.tsx
  fe/src/components/atoms/icons/Search.tsx
  fe/src/components/atoms/icons/index.ts
  fe/src/components/molecules/Button/button.stories.tsx
  fe/src/components/molecules/Button/index.tsx
  fe/src/components/molecules/IconButton/index.tsx
  fe/src/components/molecules/IconLabel/iconlabel.stories.tsx
  fe/src/components/molecules/IconLabel/index.tsx
  fe/src/components/molecules/InputContainer/index.tsx
  fe/src/components/molecules/InputContainer/inputContainer.stories.tsx
  fe/src/components/molecules/LoginForm/index.tsx
  fe/src/components/molecules/LoginForm/loginForm.stories.tsx
  fe/src/components/molecules/SearchBar/index.tsx
  fe/src/components/molecules/SearchBar/searchBar.stories.tsx
  fe/src/components/molecules/TitleSubText/index.tsx
  fe/src/components/molecules/TitleSubText/titleSubText.stories.tsx
  fe/src/components/molecules/UserInfo/index.tsx
  fe/src/components/molecules/UserInfo/userInfo.stories.tsx
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/SideBar/sideBar.stories.tsx
  fe/src/pages/_document.js
  fe/src/pages/login.tsx
Labels: FE, UI

#66 [feat] 조회(트윗, 팔로워, 팔로잉) API 구현 및 깃허브 인증 코드 작성
  be/.env.example
  be/package-lock.json
  be/package.json
  be/src/models/tweet.ts
  be/src/models/user.ts
  be/src/providers/dbProvider.ts
  be/src/resolvers/index.ts
  be/src/schema/index.ts
  be/src/services/auth.ts
  be/src/services/index.ts
  be/src/services/tweet.ts
  be/src/services/user.ts
Labels: API, BE

#68 [feat] 새글, 답글, 리트윗 추가 및 팔로우와 언팔로우 API
  be/.env.example
  be/src/models/notification.ts
  be/src/models/tweet.ts
  be/src/providers/dbProvider.ts
  be/src/resolvers/index.ts
  be/src/schema/index.ts
  be/src/services/index.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/index.ts
  be/src/services/user/addUser.ts
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
Labels: API, BE, Refactor

#69 [feat] 로그인 페이지 조립 및 GitHub 로그인 관련 로직 구현
  fe/package-lock.json
  fe/package.json
  fe/src/components/atoms/Form/index.tsx
  fe/src/components/atoms/icons/Twitter.tsx
  fe/src/components/molecules/Footer/index.tsx
  fe/src/components/molecules/SearchBar/index.tsx
  fe/src/components/organisms/LoginLeftSection/index.tsx
  fe/src/components/organisms/LoginLeftSection/loginLeftSecion.stories.tsx
  fe/src/components/organisms/LoginRightSection/index.tsx
  fe/src/components/organisms/LoginRightSection/loginRightSection.stories.tsx
  fe/src/pages/_app.tsx
  fe/src/pages/_document.js
  fe/src/pages/callback/callback.ts
  fe/src/pages/callback/index.tsx
  fe/src/pages/login.tsx
  fe/src/styles/global.css
Labels: Bug, FE, Refactor, UI

#70 [feat] 회원가입, 토큰 발급, 토큰 확인 미들웨어 등의 로그인 기능 구현
  be/package-lock.json
  be/package.json
  be/src/app.ts
  be/src/resolvers/index.ts
  be/src/schema/index.ts
  be/src/services/auth.ts
  be/src/services/index.ts
  be/src/services/user/addUser.ts
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
Labels: API, BE, auth

#73 [feat] 로그인 연결 및 메인페이지 관련 컴포넌트 작성 및 조립
  fe/next.config.js
  fe/package-lock.json
  fe/package.json
  fe/src/@type/graphql.d.ts
  fe/src/components/atoms/Form/index.tsx
  fe/src/components/atoms/Form/styled.ts
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/atoms/Input/input.stories.tsx
  fe/src/components/atoms/ProfileImg/index.tsx
  fe/src/components/atoms/ProfileImg/styled.ts
  fe/src/components/atoms/TextArea/index.tsx
  fe/src/components/atoms/TextArea/styled.ts
  fe/src/components/atoms/TextArea/text.stories.tsx
  fe/src/components/atoms/icons/Comment.tsx
  fe/src/components/atoms/icons/Explore.tsx
  fe/src/components/atoms/icons/Heart.tsx
  fe/src/components/atoms/icons/Home.tsx
  fe/src/components/atoms/icons/Notifications.tsx
  fe/src/components/atoms/icons/Picture.tsx
  fe/src/components/atoms/icons/Profiles.tsx
  fe/src/components/atoms/icons/Retweet.tsx
  fe/src/components/atoms/icons/Search.tsx
  fe/src/components/atoms/icons/Twitter.tsx
  fe/src/components/atoms/icons/index.ts
  fe/src/components/molecules/Button/button.stories.tsx
  fe/src/components/molecules/Button/index.tsx
  fe/src/components/molecules/IconButton/iconButton.stories.tsx
  fe/src/components/molecules/IconButton/index.tsx
  fe/src/components/molecules/IconLabel/iconlabel.stories.tsx
  fe/src/components/molecules/SearchBar/index.tsx
  fe/src/components/molecules/SearchBar/styled.ts
  fe/src/components/molecules/UserInfo/index.tsx
  fe/src/components/molecules/UserInfo/styled.ts
  fe/src/components/organisms/LoginLeftSection/index.tsx
  fe/src/components/organisms/LoginLeftSection/styled.ts
  fe/src/components/organisms/LoginRightSection/index.tsx
  fe/src/components/organisms/LoginRightSection/styled.ts
  fe/src/components/organisms/MainContainer/index.tsx
  fe/src/components/organisms/MainContainer/styled.ts
  fe/src/components/organisms/NewTweetContainer/index.tsx
  fe/src/components/organisms/NewTweetContainer/newTweetContainer.stories.tsx
  fe/src/components/organisms/NewTweetContainer/styled.ts
  fe/src/components/organisms/SideBar/index.tsx
  fe/src/components/organisms/SideBar/sideBar.stories.tsx
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/components/organisms/TweetContainer/styled.ts
  fe/src/components/organisms/TweetContainer/tweetcontainer.stories.tsx
  fe/src/graphql/github.gql
  fe/src/pages/_app.tsx
  fe/src/pages/_document.tsx
  fe/src/pages/callback/index.tsx
  fe/src/pages/home/index.tsx
  fe/src/pages/home/styled.ts
  fe/src/pages/login.tsx
  fe/src/pages/login/index.tsx
  fe/src/pages/login/styled.ts
Labels: Bug, FE, Refactor, UI

#72 [feat] 글목록 조회를 모든 필요한 데이터를 포함해서 제공 및 유저 모든 트윗 조회 기능, 인증 미들웨어 추가
  be/src/resolvers/index.ts
  be/src/schema/index.ts
  be/src/services/index.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/index.ts
Labels: API, BE, Refactor, auth

#74 [feat] 서버에서 데이터 받아와서 렌더링
  fe/src/components/organisms/TweetContainer/index.tsx
  fe/src/graphql/getList.gql
  fe/src/pages/home/index.tsx
Labels: FE

#75 [feat] 2주차 BE 기능 완성
  be/.env.example
  be/.eslintrc
  be/app.ts
  be/controllers/index.ts
  be/package-lock.json
  be/package.json
  be/routes/index.ts
  be/routes/schemas/index.ts
  be/services/index.ts
  be/src/app.ts
  be/src/models/index.ts
  be/src/models/notification.ts
  be/src/models/tweet.ts
  be/src/models/user.ts
  be/src/providers/dbProvider.ts
  be/src/resolvers/index.ts
  be/src/schema/index.ts
  be/src/services/auth.ts
  be/src/services/index.ts
  be/src/services/tweet/addTweet.ts
  be/src/services/tweet/getTweet.ts
  be/src/services/tweet/index.ts
  be/src/services/user/addUser.ts
  be/src/services/user/getUser.ts
  be/src/services/user/index.ts
  be/src/services/user/modifyUser.ts
Labels: API, BE, DB, Development Setting
